#!/usr/bin/env zsh
# This runs a .limb file which contains a serialized, binary, Prolog term.

if [ $# -ne 1 ]; then
  echo usage: lim {file-name}
  exit 1
fi

# swipl lim_run_swi.pl "$1"
alias scryerp=/Users/volkmannm/Documents/dev/lang/prolog/scryer-prolog/target/release/scryer-prolog
scryerp lim_run_scryer.pl -- "$1"
