#!/usr/bin/env zsh
source $HOME/.zshrc
# This runs a .limb file which contains a serialized, binary, Prolog term.

if [ $# -ne 1 ]; then
  echo usage: lim {file-name}
  exit 1
fi

# swipl lim_run_swi.pl "$1"
scryerp -g run,halt lim_run_scryer.pl -- "$1"
