#!/usr/bin/env zsh
source $HOME/.zshrc
# This compiles a .lim file, producing a .limc file
# which contains a serialized, binary, Prolog term.

if [ $# -ne 1 ]; then
  echo usage: limc {file-name}
  exit 1
fi

# swipl lim_compile_swi.pl "$1"
scryerp -g run,halt lim_compile_scryer.pl -- "$1"
